const ROUTES = {
    API_SIGNAL_CREATE: "/api/signal/create",
    API_CONFIG_UPDATE: "/api/config/update",
    API_STYLE_UPDATE: "/api/style/update",
    API_MEDIA_UPDATE: "/api/media/update",
    INDEX: "/",
    PANEL_ZOMBIE: "/public/zombie",
    PANEL_DASHBOARD: "/public/dashboard",
    PANEL_ACTIONS: "/public/actions",
    PANEL_LAYOUT: "/public/layout",
    PANEL_DRAW: "/public/draw",
    PANEL_EMBED: "/public/embed",
    PANEL_FEATURE_EMBED: "/public/feature/embed",
    PANEL_MEDIA_EMBED: "/public/media/embed",
    PANEL_DRAW_EMBED: "/public/draw/embed",
    PANEL_SOUND_EMBED: "/public/sound/embed",
    PANEL_BPM_EMBED: "/public/bpm/embed",
    API_BPM_PING: "/public/bpm/ping",
    TWITCH_LOGIN: "/twitch/login",
    TWITCH_REDIRECT: "https://localhost/t/w/i/t/c/h/l/o/g/i/n/s/u/c/c/e/s/s/",
    TWITCH_LOGIN_SUCCESS: "https://localhost/t/w/i/t/c/h/l/o/g/i/n/s/u/c/c/e/s/s/".split('https://localhost')[1],
};
module.exports = ROUTES;