const ROUTES = {
    MEMORY_SIGNAL_CREATE: "/demo/memory/signal/create",
    MEMORY_CONFIG_UPDATE: "/demo/memory/config/update",
    MEMORY_STYLE_UPDATE: "/demo/memory/style/update",
    MEMORY_MEDIA_UPDATE: "/demo/memory/media/update",
    API_SIGNAL_CREATE: "/api/signal/create",
    API_CONFIG_UPDATE: "/api/config/update",
    API_STYLE_UPDATE: "/api/style/update",
    API_MEDIA_UPDATE: "/api/media/update",
    INDEX: "/demo/index.html",
    PANEL_DASHBOARD: "/demo/panel-dashboard.html",
    PANEL_ACTIONS: "/demo/panel-actions.html",
    PANEL_LAYOUT: "/demo/panel-layout.html",
    PANEL_DRAW: "/demo/panel-draw.html",
    PANEL_EMBED: "/demo/embed.html",
    PANEL_FEATURE_EMBED: "/demo/embed-feature.html",
    PANEL_MEDIA_EMBED: "/demo/embed-media.html",
    PANEL_DRAW_EMBED: "/demo/embed-draw.html",
    PANEL_SOUND_EMBED: "/demo/embed-sound.html",
    TWITCH_LOGIN: "/demo/t/w/i/t/c/h/l/o/g/i/n/",
    TWITCH_LOGIN_SUCCESS: "/t/w/i/t/c/h/l/o/g/i/n/s/u/c/c/e/s/s/",
};
module.exports = {ROUTES};