const {execSync} = require('child_process');
const fs = require('fs');
execSync('npm run reset');
fs.existsSync('.media') && execSync('rm -rf .media');
fs.existsSync('.package') && execSync('rm -rf .package');
fs.existsSync('.server.js') && execSync('rm -rf .server.js');
fs.existsSync('.compiled') && execSync('rm -rf .compiled');
execSync('mkdir .compiled');
execSync('cp -r ./src .compiled/src');
const packageObj = JSON.parse(String(fs.readFileSync('./package.json', {encoding: 'utf-8'})));
packageObj.main = packageObj.pkg.scripts;
delete packageObj.devDependencies;
delete packageObj.scripts;
fs.writeFileSync('./.compiled/package.json', JSON.stringify(packageObj, null, 4), {encoding: 'utf-8'});
execSync('cd .compiled/ && npm i --no-package-lock', {stdio: 'inherit'});
execSync('rm -rf ./.compiled/node_modules/.bin');
execSync('rm -rf ./.compiled/src/client/');
execSync('rm -rf ./.compiled/src/server/');
execSync('rm -rf ./.compiled/src/templates/');
execSync('pkg -d .compiled', {stdio: 'inherit'});