const fs = require('fs');
const request = require('sync-request');
const {execSync} = require('child_process');
execSync("rm -rf ./node_modules");
execSync("npm install");
execSync("node ./compiler/combine.js");
let data = JSON.parse(fs.readFileSync("./.combined.json", "utf-8"));
fs.rmSync("./.dist", {recursive: true, force: true});
Object.keys(data).map(path => fs.mkdirSync(`.dist/${path.split('\\').slice(0, -1).join('\\')}`, {recursive: true, force: true}));
Object.keys(data).map(path => fs.writeFileSync(`.dist/${path}`, data[path], {encoding: 'utf-8'}));
fs.copyFileSync(".env", "./.dist/.env");
fs.copyFileSync("./package.json", "./.dist/package.json");
fs.copyFileSync("./localhost.key", "./.dist/localhost.key");
fs.copyFileSync("./localhost.crt", "./.dist/localhost.crt");
fs.copyFileSync("./src/client/icon512_maskable.png", "./.dist/src/client/icon512_maskable.png");
fs.copyFileSync("./src/client/icon512_rounded.png", "./.dist/src/client/icon512_rounded.png");
fs.copyFileSync("./src/client/manifest.json", "./.dist/src/client/manifest.json");
console.log("Temp files copied");
console.log("Installing packages");
execSync(`cd ./.dist/ && npm i --no-save`);
console.log("Installing packages...done");
console.log("Starting test server...");
execSync(`cd ./.dist/ && node ./src/index.js`, {stdio: 'inherit'});