const {execSync} = require('child_process');
const fs = require('fs');
const hash = process.argv[2] || 'demo';
execSync('npm run reset');
fs.mkdirSync('.compiled');
execSync('cp -r ./src .compiled/src');
execSync('cp -r ./.launch.js .compiled/src/launch.js');
const packageObj = JSON.parse(String(fs.readFileSync('./package.json', {encoding: 'utf-8'})));
packageObj.main = packageObj.pkg.scripts;
delete packageObj.devDependencies;
delete packageObj.scripts;
fs.writeFileSync('./.compiled/package.json', JSON.stringify(packageObj, null, 4), {encoding: 'utf-8'});
execSync('cd .compiled/ && npm i --no-package-lock', {stdio: 'inherit'});
execSync('pkg -d .compiled', {stdio: 'inherit'});
execSync('mv .package/app.exe .package/StreamDream.exe', { stdio: 'inherit' });