require("dotenv").config();
const ROUTES = require("./modules/routes");
const express = require("express");
const {requestLogger} = require("./modules/logger");
const {minify} = require("./modules/minify");
const {cache} = require("./modules/cache");
const {startServices} = require("./modules/start");
const {publicSignalCreate} = require("./modules/public/signal");
const {publicConfigUpdate} = require("./modules/public/config");
const {publicStyleUpdate} = require("./modules/public/style");
const {publicBpmPing} = require("./modules/sensor/ping");
const {twitchLogin, twitchLoginSuccess} = require("./modules/twitch/login");
const app = express();
app.use(requestLogger);
// app.use(cache);
// app.use(minify);
app.all(ROUTES.TWITCH_LOGIN, twitchLogin);
app.all(ROUTES.TWITCH_LOGIN_SUCCESS, twitchLoginSuccess);
app.all(ROUTES.INDEX, (req, res) => res.render("index"));
app.all(ROUTES.PANEL_DASHBOARD, (req, res) => res.render("panel/dashboard"));
app.all(ROUTES.PANEL_SETTINGS, (req, res) => res.render("panel/settings"));
app.all(ROUTES.PANEL_MODULES, (req, res) => res.render("panel/modules"));
app.all(ROUTES.PANEL_DRAW, (req, res) => res.render("panel/draw"));
app.all(ROUTES.PANEL_FEATURE_EMBED, (req, res) => res.render("embed/iframe-twitch"));
app.all(ROUTES.PANEL_BPM_EMBED, (req, res) => res.render("embed/iframe-bpm"));
app.all(ROUTES.PANEL_DRAW_EMBED, (req, res) => res.render("embed/iframe-draw"));
app.all(ROUTES.API_SIGNAL_CREATE, publicSignalCreate);
app.all(ROUTES.API_CONFIG_UPDATE, publicConfigUpdate);
app.all(ROUTES.API_STYLE_UPDATE, publicStyleUpdate);
app.all(ROUTES.API_BPM_PING, publicBpmPing);
startServices(app);
